# Generated by Django 3.2.6 on 2021-08-07 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ergast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitstops',
            name='driver_id',
            field=models.ForeignKey(db_column='driverId', default=0, on_delete=django.db.models.deletion.CASCADE, to='ergast.drivers', verbose_name='Foreign key link to drivers table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pitstops',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Duration of stop e.g. "21.783"'),
        ),
        migrations.AddField(
            model_name='pitstops',
            name='lap',
            field=models.IntegerField(default=0, verbose_name='Lap number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pitstops',
            name='milliseconds',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duration of stop in milliseconds'),
        ),
        migrations.AddField(
            model_name='pitstops',
            name='race_id',
            field=models.ForeignKey(db_column='raceId', default=0, on_delete=django.db.models.deletion.CASCADE, to='ergast.races', verbose_name='Foreign key link to races table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pitstops',
            name='stop',
            field=models.IntegerField(default=0, verbose_name='Stop number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pitstops',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Time of stop e.g. "13:52:25"'),
        ),
        migrations.AddField(
            model_name='qualifying',
            name='constructor_id',
            field=models.ForeignKey(db_column='constructorId', default=0, on_delete=django.db.models.deletion.CASCADE, to='ergast.constructors', verbose_name='Foreign key link to constructors table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualifying',
            name='driver_id',
            field=models.ForeignKey(db_column='driverId', default=0, on_delete=django.db.models.deletion.CASCADE, to='ergast.drivers', verbose_name='Foreign key link to drivers table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualifying',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Driver number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualifying',
            name='position',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qualifying position'),
        ),
        migrations.AddField(
            model_name='qualifying',
            name='q1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Q1 lap time e.g. "1:21.374"'),
        ),
        migrations.AddField(
            model_name='qualifying',
            name='q2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Q2 lap time'),
        ),
        migrations.AddField(
            model_name='qualifying',
            name='q3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Q3 lap time'),
        ),
        migrations.AddField(
            model_name='qualifying',
            name='race_id',
            field=models.ForeignKey(db_column='raceId', default=0, on_delete=django.db.models.deletion.CASCADE, to='ergast.races', verbose_name='Foreign key link to races table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='races',
            name='pit_stops',
            field=models.ManyToManyField(related_name='pit_stops', through='ergast.PitStops', to='ergast.Drivers'),
        ),
        migrations.AddField(
            model_name='results',
            name='constructor_id',
            field=models.ForeignKey(db_column='constructorId', default=0, on_delete=django.db.models.deletion.CASCADE, to='ergast.constructors', verbose_name='Foreign key link to constructors table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='driver_id',
            field=models.ForeignKey(db_column='driverId', default=0, on_delete=django.db.models.deletion.CASCADE, to='ergast.drivers', verbose_name='Foreign key link to drivers table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='fastest_lap',
            field=models.IntegerField(blank=True, db_column='fastestLap', null=True, verbose_name='Lap number of fastest lap'),
        ),
        migrations.AddField(
            model_name='results',
            name='fastest_lap_speed',
            field=models.CharField(blank=True, db_column='fastestLapSpeed', max_length=255, null=True, verbose_name='Fastest lap speed (km/h) e.g. "213.874"'),
        ),
        migrations.AddField(
            model_name='results',
            name='fastest_lap_time',
            field=models.CharField(blank=True, db_column='fastestLapTime', max_length=255, null=True, verbose_name='Fastest lap time e.g. "1:27.453"'),
        ),
        migrations.AddField(
            model_name='results',
            name='grid',
            field=models.IntegerField(default=0, verbose_name='Starting grid position'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='laps',
            field=models.IntegerField(default=0, verbose_name='Number of completed laps'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='milliseconds',
            field=models.IntegerField(blank=True, null=True, verbose_name='Finishing time in milliseconds'),
        ),
        migrations.AddField(
            model_name='results',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Driver number'),
        ),
        migrations.AddField(
            model_name='results',
            name='points',
            field=models.FloatField(default=0, verbose_name='Driver points for race'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='position',
            field=models.IntegerField(blank=True, null=True, verbose_name='Official classification, if applicable'),
        ),
        migrations.AddField(
            model_name='results',
            name='position_order',
            field=models.IntegerField(db_column='positionOrder', default=0, verbose_name='Driver position for ordering purposes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='position_text',
            field=models.CharField(blank=True, db_column='positionText', max_length=255, verbose_name='Driver position string e.g. "1" or "R"'),
        ),
        migrations.AddField(
            model_name='results',
            name='race_id',
            field=models.ForeignKey(db_column='raceId', default=0, on_delete=django.db.models.deletion.CASCADE, to='ergast.races', verbose_name='Foreign key link to races table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fastest lap rank, compared to other drivers'),
        ),
        migrations.AddField(
            model_name='results',
            name='status_id',
            field=models.ForeignKey(db_column='statusId', default=0, on_delete=django.db.models.deletion.CASCADE, to='ergast.status', verbose_name='Foreign key link to status table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Finishing time or gap'),
        ),
        migrations.AddField(
            model_name='status',
            name='status',
            field=models.CharField(default=0, max_length=255, verbose_name='Finishing status e.g. "Retired"'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qualifying',
            name='id',
            field=models.AutoField(db_column='qualifyId', primary_key=True, serialize=False, verbose_name='Primary key'),
        ),
        migrations.AlterField(
            model_name='races',
            name='lap_times',
            field=models.ManyToManyField(related_name='lap_times', through='ergast.LapTimes', to='ergast.Drivers'),
        ),
        migrations.AlterField(
            model_name='results',
            name='id',
            field=models.AutoField(db_column='resultId', primary_key=True, serialize=False, verbose_name='Primary key'),
        ),
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Primary key'),
        ),
        migrations.AddConstraint(
            model_name='pitstops',
            constraint=models.UniqueConstraint(fields=('race_id', 'driver_id', 'stop'), name='unique_pit_stop'),
        ),
        migrations.AlterModelTable(
            name='laptimes',
            table=None,
        ),
    ]
