# Generated by Django 3.2.6 on 2021-08-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ergast", "0008_auto_20210808_0107"),
    ]

    operations = [
        migrations.RenameField(
            model_name="status",
            old_name="id",
            new_name="statusId",
        )
    ]
