# Generated by Django 3.2.6 on 2021-08-14 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ergast", "0011_alter_pitstops_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="circuits",
            options={"ordering": ["circuitRef"]},
        ),
        migrations.AlterModelOptions(
            name="races",
            options={"ordering": ["year", "round"]},
        ),
    ]
