# Generated by Django 3.2.6 on 2021-09-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ergast', '0012_auto_20210814_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='code',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Driver code e.g. "ALO"'),
        ),
    ]
