name: 💡 Feature request
description: Suggest an idea for this project
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the feature you are requesting. (https://github.com/jolpica/jolpica-f1/issues).
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Is your feature request related to a problem? Please describe the problem.
    description: A clear and concise description of what the problem is.
    placeholder: I am trying to do [...] but [...]
  validations:
    required: false
- type: textarea
  attributes:
    label: Describe the solution you'd like
    description: |
      A clear and concise description of what you want to happen. Include any alternative solutions you've considered.
  validations:
    required: true
- type: textarea
  attributes:
    label: Will this require a new data source?
    description: |
      Does this feature request involve data we already have in our database? If not, where could we automatically source this data?
  validations:
    required: false