blank_issues_enabled: true
contact_links:
  - name: Question about the API
    url:  https://github.com/jolpica/jolpica-f1/discussions/new/choose
    about: Please open a discussion to ask questions about the API.
