"""Django settings for jolpica project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from typing import Literal

import environ  # type: ignore

from .deployment_utils import get_linux_ec2_private_ip
from .logging import LOG_CONFIG

if Path("VERSION").exists():
    with open("VERSION") as f:
        VERSION = f.read().strip()
else:
    VERSION = "dev"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
if env.str("DEPLOYMENT_ENV", default="LOCAL") != "PROD":
    # OS environment variables take precedence over variables from .env
    env.read_env(str(BASE_DIR / ".env"))

DEPLOYMENT_ENV: Literal["LOCAL", "SANDBOX", "BUILD", "PROD"] = env.str("DEPLOYMENT_ENV", default="LOCAL")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
if DEPLOYMENT_ENV == "PROD":
    SECRET_KEY = env("DJANGO_SECRET_KEY")
else:
    SECRET_KEY = env("DJANGO_SECRET_KEY", default="jolpica")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False if DEPLOYMENT_ENV == "PROD" else env("DJANGO_DEBUG", default=True)

live = env("LIVE", cast=str, default="localhost,127.0.0.1").split(",")
ALLOWED_HOSTS: list[str] = ["api.jolpi.ca", *live]
if DEPLOYMENT_ENV == "PROD" and (private_ip := get_linux_ec2_private_ip()):
    ALLOWED_HOSTS.append(private_ip)

CSRF_TRUSTED_ORIGINS = ["https://api.jolpi.ca"]

INTERNAL_IPS = ["127.0.0.1", "localhost"]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

CORS_ALLOW_ALL_ORIGINS = True

# Application definition
ROOT_URLCONF = "jolpica_api.urls"

WSGI_APPLICATION = "jolpica_api.wsgi.application"


# Installed Django Apps

INSTALLED_APPS = [
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "knox",
    "drf_spectacular",
    "jolpica.formula_one",
    "jolpica_api.dumps",
    "jolpica_api.authentication",
    "jolpica_api.ergastapi",
    "jolpica_api.data_import",
]
if DEPLOYMENT_ENV in ("LOCAL", "SANDBOX"):
    INSTALLED_APPS += ["django_dbml", "debug_toolbar"]


# Middleware

MIDDLEWARE = [
    "jolpica_api.deployment_utils.client_ip_middleware",
    "jolpica_api.deployment_utils.ip_blocks_middleware",
    "jolpica_api.deployment_utils.queryparam_blocks_middleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_ratelimit.middleware.RatelimitMiddleware",
]
if DEPLOYMENT_ENV in ("LOCAL", "SANDBOX"):
    # Debug toolbar should go as early as possible in middleware
    MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")

RATELIMIT_VIEW = "jolpica_api.views.ratelimited_error"


# Templates

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["jolpica_api/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": env.db(
        "DATABASE_SECRET_URL",
        default="postgres://postgres:postgres@localhost/jolpica",
    ),
}
DATABASES["default"]["ATOMIC_REQUESTS"] = False
DATABASES["default"]["CONN_MAX_AGE"] = 60  # Interim solution to avoid connection errors with psycopg2

# Cache
# https://docs.djangoproject.com/en/4.2/topics/cache/#redis

CACHES = {
    "default": env.cache(
        "CACHE_SECRET_URL",
        default="redis://127.0.0.1:6379/1?client_class=django_redis.client.DefaultClient",
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images) using django-storages
# https://docs.djangoproject.com/en/4.2/howto/static-files
# https://django-storages.readthedocs.io/en/latest/
CLOUDFRONT_DOMAIN = env("CLOUDFRONT_DOMAIN", default="https://jolpi.ca")

STATICFILES_DIRS = [BASE_DIR / "jolpica_api/static"]

if not DEBUG:
    STATIC_URL = f"{CLOUDFRONT_DOMAIN}/static/"
    if DEPLOYMENT_ENV != "PROD":
        # Configuration to upload AWS S3 Cloudfront static files during deployment
        STORAGES = {
            "staticfiles": {
                "BACKEND": "storages.backends.s3.S3Storage",
                "OPTIONS": {
                    "access_key": env("AWS_STATIC_ACCESS_KEY_ID", default="unset"),
                    "secret_key": env("AWS_STATIC_SECRET_ACCESS_KEY", default="unset"),
                    "bucket_name": env("AWS_STATIC_S3_BUCKET", default="unset"),
                    "location": "static",
                    "region_name": env("AWS_S3_REGION_NAME", default="eu-west-1"),
                    "signature_version": "s3v4",
                    "querystring_expire": 604800,
                    "custom_domain": CLOUDFRONT_DOMAIN,
                },
            },
        }
else:
    # Locally served static files
    STATIC_URL = "static/"
    STATIC_ROOT = "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# DJANGO REST FRAMEWORK
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ("knox.auth.TokenAuthentication",),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "PAGE_SIZE": 30,
}

# django-rest-knox https://jazzband.github.io/django-rest-knox/settings/
REST_KNOX = {
    "TOKEN_TTL": None,
    "TOKEN_PREFIX": "jolp",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "jolpica-f1 API",
    "DESCRIPTION": "API for Formula 1 data.",
    "VERSION": VERSION,
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": "/f1/",
    "PREPROCESSING_HOOKS": [
        "jolpica_api.deployment_utils.drf_spectacular_filter_preprocess",
    ],
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
    },
    # Target only the /f1/alpha/ endpoints for inclusion in the schema
    # 'SERVERS': [
    #     {'url': '/'}, # Or specific domain if deployed
    # ],
}

LOGGING = LOG_CONFIG if DEPLOYMENT_ENV != "LOCAL" else None
