# Generated by Django 5.2.5 on 2025-09-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dump",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "file_hash",
                    models.CharField(
                        help_text="SHA256 hash of the dump file",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "dump_type",
                    models.CharField(
                        choices=[("csv", "CSV"), ("sql", "SQL")],
                        help_text="Type of database dump (csv, sql, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Path / key to where file is stored", max_length=500
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(help_text="Size of dump file in bytes"),
                ),
                (
                    "upload_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current upload status",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this dump record was created"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When upload was completed successfully",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional dump-specific metadata",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [("can_upload_dumps", "Can upload database dumps")],
                "indexes": [
                    models.Index(
                        fields=["dump_type", "upload_status"],
                        name="dumps_dump_dump_ty_96fff6_idx",
                    ),
                    models.Index(
                        fields=["file_hash"], name="dumps_dump_file_ha_590e21_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="dumps_dump_created_ab9873_idx"
                    ),
                ],
            },
        ),
    ]
