# Generated by Django 5.2.5 on 2025-09-07 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dumps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dump',
            options={'ordering': ['-created_at'], 'permissions': [('can_upload_dumps', 'Can upload database dumps'), ('can_download_latest_dump', 'Can download latest database dump')]},
        ),
    ]
