# Generated by Django 5.1.6 on 2025-03-02 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataImportLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("is_success", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("total_records", models.PositiveIntegerField(null=True)),
                ("updated_records", models.JSONField(null=True)),
                ("error_type", models.CharField(max_length=255, null=True)),
                ("errors", models.JSONField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
