# Generated by Django 5.1.6 on 2025-03-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_import", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataimportlog",
            name="description",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
