# Generated by Django 5.2.3 on 2025-08-03 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DumpConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delay_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed Days"),
                            ("season", "End of Season"),
                            ("milestone", "Milestone Based"),
                        ],
                        default="fixed",
                        help_text="How to calculate delay for public dumps",
                        max_length=10,
                    ),
                ),
                (
                    "delay_days",
                    models.PositiveIntegerField(
                        default=30, help_text="Number of days to delay public dumps"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable/disable automatic dump generation",
                    ),
                ),
                (
                    "slack_webhook_url",
                    models.URLField(
                        blank=True, help_text="Slack webhook URL for notifications"
                    ),
                ),
                (
                    "s3_bucket_public",
                    models.CharField(
                        default="jolpica-dumps-public",
                        help_text="S3 bucket for public (delayed) dumps",
                        max_length=255,
                    ),
                ),
                (
                    "s3_bucket_private",
                    models.CharField(
                        default="jolpica-dumps-private",
                        help_text="S3 bucket for private (latest) dumps",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dump Configuration",
                "verbose_name_plural": "Dump Configurations",
            },
        ),
        migrations.CreateModel(
            name="DumpRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dump_type",
                    models.CharField(
                        choices=[
                            ("latest", "Latest (Paid)"),
                            ("delayed", "Delayed (Public)"),
                        ],
                        help_text="Type of dump (latest or delayed)",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("uploading", "Uploading"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA256 hash of the dump file",
                        max_length=64,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "s3_key",
                    models.CharField(
                        blank=True,
                        help_text="S3 object key for the dump file",
                        max_length=500,
                    ),
                ),
                (
                    "s3_url",
                    models.URLField(blank=True, help_text="S3 URL for the dump file"),
                ),
                (
                    "has_changes",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this dump contains changes from the previous one",
                    ),
                ),
                (
                    "previous_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of the previous dump for comparison",
                        max_length=64,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if dump failed"
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        default="scheduled",
                        help_text="How this dump was triggered: scheduled, manual, data_import",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dump Record",
                "verbose_name_plural": "Dump Records",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["dump_type", "status"],
                        name="formula_one_dump_ty_ba231d_idx",
                    ),
                    models.Index(
                        fields=["started_at"], name="formula_one_started_d34c0f_idx"
                    ),
                    models.Index(
                        fields=["status", "completed_at"],
                        name="formula_one_status_605fb1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DumpDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "downloaded_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                (
                    "donator_id",
                    models.CharField(
                        blank=True,
                        help_text="External donator ID (Ko-fi, Patreon, etc.)",
                        max_length=100,
                    ),
                ),
                ("referer", models.URLField(blank=True)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                (
                    "dump_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="formula_one_dump.dumprecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dump Download",
                "verbose_name_plural": "Dump Downloads",
                "indexes": [
                    models.Index(
                        fields=["downloaded_at"], name="formula_one_downloa_63ae22_idx"
                    ),
                    models.Index(
                        fields=["dump_record", "donator_id"],
                        name="formula_one_dump_re_86bd17_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "downloaded_at"],
                        name="formula_one_ip_addr_fe42e4_idx",
                    ),
                ],
            },
        ),
    ]
