# Generated by Django 5.1.7 on 2025-03-29 15:18

import django.contrib.gis.db.models.fields
import django.contrib.postgres.operations
import django.db.migrations.operations.special
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("formula_one", "0001_0009_squashed"),
        ("formula_one", "0002_remove_sessionentry_fastest_lap_and_more"),
        ("formula_one", "0003_lap_is_deleted"),
        ("formula_one", "0004_driver_country_code_team_country_code_and_more"),
        ("formula_one", "0005_circuit_country_code"),
        ("formula_one", "0006_remove_pitstop_pit_stop_unique_session_entry_lap_and_more"),
        ("formula_one", "0007_circuit_latitude_circuit_longitude"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseTeam",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChampionshipAdjustment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "adjustment",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "None"), (1, "Point Deduction"), (101, "Disqualified"), (102, "Excluded")]
                    ),
                ),
                (
                    "points",
                    models.FloatField(
                        blank=True,
                        help_text="Points to deduct if POINT_DEDUCTION adjustment, otherwise null",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChampionshipSystem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("reference", models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "eligibility",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Entry must score at least 1 championship point"),
                            (2, "Entry must have a classified finish in at least 1 round"),
                        ]
                    ),
                ),
                (
                    "driver_season_split",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Season is not split"),
                            (2, "Split in halves (remainder in first half)"),
                            (3, "Split in halves (remainder in second half)"),
                        ]
                    ),
                ),
                (
                    "driver_best_results",
                    models.SmallIntegerField(
                        choices=[
                            (-2, "One less than total races per split"),
                            (-1, "All results are counted"),
                            (0, "No results are counted"),
                            (4, "Four"),
                            (5, "Five"),
                            (6, "Six"),
                            (7, "Seven"),
                            (8, "Eight"),
                            (11, "Eleven"),
                        ]
                    ),
                ),
                (
                    "team_season_split",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Season is not split"),
                            (2, "Split in halves (remainder in first half)"),
                            (3, "Split in halves (remainder in second half)"),
                        ]
                    ),
                ),
                (
                    "team_best_results",
                    models.SmallIntegerField(
                        choices=[
                            (-2, "One less than total races per split"),
                            (-1, "All results are counted"),
                            (0, "No results are counted"),
                            (4, "Four"),
                            (5, "Five"),
                            (6, "Six"),
                            (7, "Seven"),
                            (8, "Eight"),
                            (11, "Eleven"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Circuit",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("reference", models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("locality", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("altitude", models.FloatField(blank=True, null=True)),
                ("wikipedia", models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("reference", models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ("forename", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
                ("abbreviation", models.CharField(blank=True, max_length=10, null=True)),
                ("nationality", models.CharField(blank=True, max_length=255, null=True)),
                ("permanent_car_number", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("wikipedia", models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DriverChampionship",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("year", models.SmallIntegerField()),
                ("round_number", models.PositiveSmallIntegerField()),
                ("session_number", models.PositiveSmallIntegerField()),
                ("position", models.SmallIntegerField(null=True)),
                ("points", models.FloatField()),
                ("win_count", models.SmallIntegerField()),
                ("highest_finish", models.SmallIntegerField(null=True)),
                ("is_eligible", models.BooleanField(default=False)),
                (
                    "adjustment_type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "None"), (1, "Point Deduction"), (101, "Disqualified"), (102, "Excluded")],
                        default=0,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lap",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("number", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("position", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("time", models.DurationField(blank=True, null=True)),
                ("average_speed", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Penalty",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("license_points", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("position", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("time", models.DurationField(blank=True, null=True)),
                ("is_time_served_in_pit", models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PitStop",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("number", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("local_timestamp", models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PointSystem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("reference", models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "driver_position_points",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "No Points Awarded"),
                            (1, "1950 - Top 5 get upto 8 points"),
                            (2, "1960 - Top 6 get upto 8 points"),
                            (3, "1961 - Top 6 get upto 9 points"),
                            (5, "1991 - Top 6 get upto 10 points"),
                            (6, "2003 - Top 8 get upto 10 points"),
                            (7, "2010 - Top 10 get upto 25 points"),
                            (21, "Sprint 2021 - Top 3 get upto 3 points"),
                            (22, "Sprint 2022 - Top 8 get upto 8 points"),
                        ]
                    ),
                ),
                (
                    "driver_fastest_lap",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "No Fastest Lap Point"),
                            (1, "Point for Fastest Lap"),
                            (2, "Point divided between all who got fastest lap"),
                            (3, "Point if in top 10"),
                            (4, "Point if top 10, and >50% race distance"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "team_position_points",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "No Points Awarded"),
                            (1, "1950 - Top 5 get upto 8 points"),
                            (2, "1960 - Top 6 get upto 8 points"),
                            (3, "1961 - Top 6 get upto 9 points"),
                            (5, "1991 - Top 6 get upto 10 points"),
                            (6, "2003 - Top 8 get upto 10 points"),
                            (7, "2010 - Top 10 get upto 25 points"),
                            (21, "Sprint 2021 - Top 3 get upto 3 points"),
                            (22, "Sprint 2022 - Top 8 get upto 8 points"),
                        ]
                    ),
                ),
                (
                    "team_fastest_lap",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "No Fastest Lap Point"),
                            (1, "Point for Fastest Lap"),
                            (2, "Point divided between all who got fastest lap"),
                            (3, "Point if in top 10"),
                            (4, "Point if top 10, and >50% race distance"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "partial",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "No Partial Points"),
                            (1, "Half Points between 30% - 60%"),
                            (2, "Half Points between 2 Laps - 75%"),
                            (3, "Red Flag Finish, 1-4 Quarters (rounded) of points, minimum 2 laps."),
                            (4, "1-4 Quarters (rounded) of points, minimum 2 laps"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "shared_drive",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "No Points"),
                            (1, "Points Shared Equally"),
                            (2, "Shared Points of all drives, unless insufficent distance"),
                            (3, "Shared Points of highest finish"),
                        ],
                        default=0,
                    ),
                ),
                ("is_double_points", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("number", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("race_number", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("wikipedia", models.URLField(blank=True, null=True)),
                ("is_cancelled", models.BooleanField(default=False)),
                (
                    "circuit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="rounds", to="formula_one.circuit"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoundEntry",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("car_number", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_entries",
                        to="formula_one.round",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("year", models.SmallIntegerField(unique=True)),
                ("wikipedia", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "championship_system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seasons",
                        to="formula_one.championshipsystem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("number", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("R", "Race"),
                            ("Q1", "Qualifying One"),
                            ("Q2", "Qualifying Two"),
                            ("Q3", "Qualifying Three"),
                            ("QA", "Qualifying Avg"),
                            ("QO", "Qualifying Order"),
                            ("QB", "Qualifying Best"),
                            ("FP1", "Practice One"),
                            ("FP2", "Practice Two"),
                            ("FP3", "Practice Three"),
                            ("PQ", "Prequalifying"),
                            ("SR", "Sprint Race"),
                            ("SQ1", "Sprint Qualifying1"),
                            ("SQ2", "Sprint Qualifying2"),
                            ("SQ3", "Sprint Qualifying3"),
                        ],
                        max_length=3,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("time", models.TimeField(blank=True, null=True)),
                ("scheduled_laps", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_cancelled", models.BooleanField(default=False)),
                (
                    "point_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="formula_one.pointsystem",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sessions", to="formula_one.round"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("reference", models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("nationality", models.CharField(blank=True, max_length=255, null=True)),
                ("wikipedia", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "base_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teams",
                        to="formula_one.baseteam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamDriver",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.PositiveSmallIntegerField(
                        blank=True, choices=[(0, "Permanent"), (1, "Reserve"), (2, "Junior")], null=True
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_drivers",
                        to="formula_one.driver",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_drivers",
                        to="formula_one.season",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="team_drivers", to="formula_one.team"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamChampionship",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("year", models.SmallIntegerField()),
                ("round_number", models.PositiveSmallIntegerField()),
                ("session_number", models.PositiveSmallIntegerField()),
                ("position", models.SmallIntegerField(null=True)),
                ("points", models.FloatField()),
                ("win_count", models.SmallIntegerField()),
                ("highest_finish", models.SmallIntegerField(null=True)),
                ("is_eligible", models.BooleanField(default=False)),
                (
                    "adjustment_type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "None"), (1, "Point Deduction"), (101, "Disqualified"), (102, "Excluded")],
                        default=0,
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_championships",
                        to="formula_one.round",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_championships",
                        to="formula_one.season",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_championships",
                        to="formula_one.session",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_championships",
                        to="formula_one.team",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="team",
            name="drivers",
            field=models.ManyToManyField(
                related_name="teams", through="formula_one.TeamDriver", to="formula_one.driver"
            ),
        ),
        migrations.CreateModel(
            name="SessionEntry",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("position", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_classified", models.BooleanField(blank=True, null=True)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "Finished"),
                            (1, "Car Finished Lap(s) behind Leader"),
                            (10, "Accident, Collision or Driver Error on Track"),
                            (11, "Mechanial, Safety or Other Retirement"),
                            (20, "Disqualified"),
                            (30, "Withdrawn or Did Not Start"),
                            (40, "Did Not Qualify"),
                            (41, "Did Not Prequalify"),
                        ],
                        null=True,
                    ),
                ),
                ("detail", models.CharField(blank=True, max_length=255, null=True)),
                ("points", models.FloatField(blank=True, null=True)),
                ("is_eligible_for_points", models.BooleanField(default=True)),
                ("grid", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("time", models.DurationField(blank=True, null=True)),
                ("fastest_lap_rank", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("laps_completed", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "fastest_lap",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="formula_one.lap",
                    ),
                ),
                (
                    "round_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_entries",
                        to="formula_one.roundentry",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_entries",
                        to="formula_one.session",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="session",
            name="round_entries",
            field=models.ManyToManyField(
                related_name="sessions", through="formula_one.SessionEntry", to="formula_one.roundentry"
            ),
        ),
        migrations.AddField(
            model_name="season",
            name="drivers",
            field=models.ManyToManyField(
                related_name="seasons", through="formula_one.TeamDriver", to="formula_one.driver"
            ),
        ),
        migrations.AddField(
            model_name="season",
            name="teams",
            field=models.ManyToManyField(
                related_name="seasons", through="formula_one.TeamDriver", to="formula_one.team"
            ),
        ),
        migrations.AddField(
            model_name="roundentry",
            name="team_driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="round_entries", to="formula_one.teamdriver"
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="rounds", to="formula_one.season"
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="team_drivers",
            field=models.ManyToManyField(
                related_name="rounds", through="formula_one.RoundEntry", to="formula_one.teamdriver"
            ),
        ),
        migrations.AddConstraint(
            model_name="pointsystem",
            constraint=models.UniqueConstraint(
                fields=(
                    "driver_position_points",
                    "driver_fastest_lap",
                    "team_position_points",
                    "team_fastest_lap",
                    "partial",
                    "shared_drive",
                    "is_double_points",
                ),
                name="point_system_unique",
            ),
        ),
        migrations.AddField(
            model_name="pitstop",
            name="lap",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to=models.Q(("session_entry", models.F("session_entry"))),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pit_stop",
                to="formula_one.lap",
            ),
        ),
        migrations.AddField(
            model_name="pitstop",
            name="session_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="pit_stops", to="formula_one.sessionentry"
            ),
        ),
        migrations.AddField(
            model_name="penalty",
            name="earned",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="penalties",
                to="formula_one.sessionentry",
            ),
        ),
        migrations.AddField(
            model_name="penalty",
            name="served",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="served_penalties",
                to="formula_one.sessionentry",
            ),
        ),
        migrations.AddField(
            model_name="lap",
            name="session_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="laps", to="formula_one.sessionentry"
            ),
        ),
        migrations.AddField(
            model_name="driverchampionship",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_championships",
                to="formula_one.driver",
            ),
        ),
        migrations.AddField(
            model_name="driverchampionship",
            name="round",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="driver_championships",
                to="formula_one.round",
            ),
        ),
        migrations.AddField(
            model_name="driverchampionship",
            name="season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="driver_championships",
                to="formula_one.season",
            ),
        ),
        migrations.AddField(
            model_name="driverchampionship",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_championships",
                to="formula_one.session",
            ),
        ),
        migrations.AddConstraint(
            model_name="championshipsystem",
            constraint=models.UniqueConstraint(
                fields=(
                    "eligibility",
                    "driver_season_split",
                    "driver_best_results",
                    "team_season_split",
                    "team_best_results",
                ),
                name="championship_point_scheme_unique",
            ),
        ),
        migrations.AddField(
            model_name="championshipadjustment",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="championship_adjustments",
                to="formula_one.driver",
            ),
        ),
        migrations.AddField(
            model_name="championshipadjustment",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="championship_adjustments",
                to="formula_one.season",
            ),
        ),
        migrations.AddField(
            model_name="championshipadjustment",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="championship_adjustments",
                to="formula_one.team",
            ),
        ),
        migrations.AddConstraint(
            model_name="teamdriver",
            constraint=models.UniqueConstraint(fields=("team", "driver", "season"), name="team_driver_unique"),
        ),
        migrations.AddConstraint(
            model_name="teamchampionship",
            constraint=models.UniqueConstraint(
                fields=("session", "team"), name="team_championship_unique_session_team"
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionentry",
            constraint=models.UniqueConstraint(
                fields=("session", "round_entry"), name="session_entry_unique_session_round_entry"
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.UniqueConstraint(fields=("round", "number"), name="session_unique_number_round"),
        ),
        migrations.AddConstraint(
            model_name="roundentry",
            constraint=models.UniqueConstraint(
                fields=("round", "team_driver", "car_number"), name="round_entry_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="round",
            constraint=models.UniqueConstraint(fields=("season", "number"), name="round_unique_season_number"),
        ),
        migrations.AddConstraint(
            model_name="pitstop",
            constraint=models.UniqueConstraint(
                fields=("session_entry", "lap"), name="pit_stop_unique_session_entry_lap"
            ),
        ),
        migrations.AddConstraint(
            model_name="pitstop",
            constraint=models.UniqueConstraint(
                fields=("session_entry", "number"), name="pit_stop_unique_session_entry_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="lap",
            constraint=models.UniqueConstraint(
                fields=("session_entry", "number"), name="lap_unique_session_entry_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="driverchampionship",
            constraint=models.UniqueConstraint(
                fields=("session", "driver"), name="driver_championship_unique_session_driver"
            ),
        ),
        migrations.RemoveField(
            model_name="sessionentry",
            name="fastest_lap",
        ),
        migrations.AddField(
            model_name="lap",
            name="is_entry_fastest_lap",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="lap",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_entry_fastest_lap", True)),
                fields=("session_entry", "is_entry_fastest_lap"),
                name="lap_unique_fastest_lap",
            ),
        ),
        migrations.AddField(
            model_name="lap",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="driver",
            name="country_code",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="3 Letter country code (ISO 3166-1 alpha-3)"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="country_code",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="3 Letter country code (ISO 3166-1 alpha-3)"
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="point_system",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessions",
                to="formula_one.pointsystem",
            ),
        ),
        migrations.AddField(
            model_name="circuit",
            name="country_code",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="3 Letter country code (ISO 3166-1 alpha-3)"
            ),
        ),
        migrations.RemoveConstraint(
            model_name="pitstop",
            name="pit_stop_unique_session_entry_lap",
        ),
        migrations.AlterField(
            model_name="driverchampionship",
            name="highest_finish",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="driverchampionship",
            name="position",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
