# Generated by Django 4.2.6 on 2023-10-11 22:54

from django.db import migrations, models
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        CreateExtension("postgis"),
        # Drop extensions enabled by default in devcontainer image
        migrations.RunSQL("DROP EXTENSION IF EXISTS postgis_tiger_geocoder", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL("DROP EXTENSION IF EXISTS postgis_topology", reverse_sql=migrations.RunSQL.noop),
    ]
