# Generated by Django 5.2 on 2025-05-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formula_one", "0001_squash_postgis_dependency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="type",
            field=models.CharField(
                choices=[
                    ("R", "Race"),
                    ("Q1", "Qualifying One"),
                    ("Q2", "Qualifying Two"),
                    ("Q3", "Qualifying Three"),
                    ("QA", "Qualifying Avg"),
                    ("QO", "Qualifying Order"),
                    ("QB", "Qualifying Best"),
                    ("FP1", "Practice One"),
                    ("FP2", "Practice Two"),
                    ("FP3", "Practice Three"),
                    ("PQ", "Prequalifying"),
                    ("SR", "Sprint Race"),
                    ("SQ1", "Sprint Qualifying One"),
                    ("SQ2", "Sprint Qualifying Two"),
                    ("SQ3", "Sprint Qualifying Three"),
                ],
                max_length=3,
            ),
        ),
    ]
