# Generated by Django 4.2.14 on 2024-08-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formula_one", "0001_0009_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="lap",
            name="is_fastest_lap",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="lap",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_fastest_lap", True)),
                fields=("session_entry", "is_fastest_lap"),
                name="lap_unique_fastest_lap",
            ),
        ),
    ]
