# Generated by Django 4.2.8 on 2023-12-24 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("formula_one", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChampionshipScheme",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "reference",
                    models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "driver_season_split",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Season is not split"),
                            (2, "Split in halves (remainder in first half)"),
                            (3, "Split in halves (remainder in second half)"),
                        ]
                    ),
                ),
                (
                    "driver_best_results",
                    models.SmallIntegerField(
                        choices=[
                            (-2, "One less than total races per split"),
                            (-1, "All results are counted"),
                            (0, "No results are counted"),
                            (4, "Four"),
                            (5, "Five"),
                            (6, "Six"),
                            (7, "Seven"),
                            (8, "Eight"),
                            (11, "Eleven"),
                        ]
                    ),
                ),
                (
                    "team_season_split",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Season is not split"),
                            (2, "Split in halves (remainder in first half)"),
                            (3, "Split in halves (remainder in second half)"),
                        ]
                    ),
                ),
                (
                    "team_best_results",
                    models.SmallIntegerField(
                        choices=[
                            (-2, "One less than total races per split"),
                            (-1, "All results are counted"),
                            (0, "No results are counted"),
                            (4, "Four"),
                            (5, "Five"),
                            (6, "Six"),
                            (7, "Seven"),
                            (8, "Eight"),
                            (11, "Eleven"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="pointscheme",
            name="point_scheme_unique",
        ),
        migrations.RenameField(
            model_name="pointscheme",
            old_name="fastest_lap",
            new_name="driver_fastest_lap",
        ),
        migrations.RenameField(
            model_name="pointscheme",
            old_name="driver",
            new_name="driver_points",
        ),
        migrations.RenameField(
            model_name="pointscheme",
            old_name="team",
            new_name="team_points",
        ),
        migrations.AddConstraint(
            model_name="pointscheme",
            constraint=models.UniqueConstraint(
                fields=(
                    "driver_points",
                    "driver_fastest_lap",
                    "team_points",
                    "team_fastest_lap",
                    "partial",
                    "shared_drive",
                    "is_double_points",
                ),
                name="point_scheme_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="championshipscheme",
            constraint=models.UniqueConstraint(
                fields=(
                    "driver_season_split",
                    "driver_best_results",
                    "team_season_split",
                    "team_best_results",
                ),
                name="championship_point_scheme_unique",
            ),
        ),
        migrations.AddField(
            model_name="season",
            name="championship_scheme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="seasons",
                to="formula_one.championshipscheme",
            ),
        ),
    ]
