# Generated by Django 4.2.15 on 2024-08-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formula_one", "0002_remove_sessionentry_fastest_lap_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lap",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
