# Generated by Django 4.2.15 on 2024-08-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formula_one", "0002_lap_is_fastest_lap_lap_lap_unique_fastest_lap"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lap",
            name="lap_unique_fastest_lap",
        ),
        migrations.RenameField(
            model_name="lap",
            old_name="is_fastest_lap",
            new_name="is_entry_fastest_lap",
        ),
        migrations.RemoveField(
            model_name="sessionentry",
            name="fastest_lap",
        ),
        migrations.AddConstraint(
            model_name="lap",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_entry_fastest_lap", True)),
                fields=("session_entry", "is_entry_fastest_lap"),
                name="lap_unique_fastest_lap",
            ),
        ),
    ]
