# Generated by Django 5.2 on 2025-05-24 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formula_one", "0002_alter_session_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="session",
            options={"ordering": ["date", "time", "type"]},
        ),
    ]
