# Generated by Django 5.2.1 on 2025-05-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formula_one", "0003_alter_session_options"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="championshipsystem",
            name="championship_point_scheme_unique",
        ),
        migrations.AddField(
            model_name="championshipsystem",
            name="team_points_per_session",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "All points are summed"),
                    (1, "Single highest points selected"),
                ],
                default=0,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="championshipsystem",
            name="driver_best_results",
            field=models.SmallIntegerField(
                choices=[
                    (-2, "One less than total rounds per split"),
                    (-1, "All rounds are counted"),
                    (0, "No rounds are counted"),
                    (4, "Four"),
                    (5, "Five"),
                    (6, "Six"),
                    (7, "Seven"),
                    (8, "Eight"),
                    (11, "Eleven"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="championshipsystem",
            name="team_best_results",
            field=models.SmallIntegerField(
                choices=[
                    (-2, "One less than total rounds per split"),
                    (-1, "All rounds are counted"),
                    (0, "No rounds are counted"),
                    (4, "Four"),
                    (5, "Five"),
                    (6, "Six"),
                    (7, "Seven"),
                    (8, "Eight"),
                    (11, "Eleven"),
                ]
            ),
        ),
        migrations.AddConstraint(
            model_name="championshipsystem",
            constraint=models.UniqueConstraint(
                fields=(
                    "eligibility",
                    "driver_season_split",
                    "driver_best_results",
                    "team_season_split",
                    "team_best_results",
                    "team_points_per_session",
                ),
                name="championship_point_scheme_unique",
            ),
        ),
    ]
