# Generated by Django 4.2.9 on 2024-01-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formula_one", "0003_championshipscheme_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ChampionshipScheme",
            new_name="ChampionshipSystem",
        ),
        migrations.RenameModel(
            old_name="PointScheme",
            new_name="PointSystem",
        ),
        migrations.RemoveConstraint(
            model_name="pointsystem",
            name="point_scheme_unique",
        ),
        migrations.RenameField(
            model_name="pointsystem",
            old_name="driver_points",
            new_name="driver_position_points",
        ),
        migrations.RenameField(
            model_name="pointsystem",
            old_name="team_points",
            new_name="team_position_points",
        ),
        migrations.RenameField(
            model_name="season",
            old_name="championship_scheme",
            new_name="championship_system",
        ),
        migrations.AddConstraint(
            model_name="pointsystem",
            constraint=models.UniqueConstraint(
                fields=(
                    "driver_position_points",
                    "driver_fastest_lap",
                    "team_position_points",
                    "team_fastest_lap",
                    "partial",
                    "shared_drive",
                    "is_double_points",
                ),
                name="point_system_unique",
            ),
        ),
    ]
