# Generated by Django 5.1.6 on 2025-03-02 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formula_one", "0003_lap_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="country_code",
            field=models.CharField(
                blank=True,
                max_length=3,
                null=True,
                verbose_name="3 Letter country code (ISO 3166-1 alpha-3)",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="country_code",
            field=models.CharField(
                blank=True,
                max_length=3,
                null=True,
                verbose_name="3 Letter country code (ISO 3166-1 alpha-3)",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="point_system",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessions",
                to="formula_one.pointsystem",
            ),
        ),
    ]
