# Generated by Django 5.1.6 on 2025-03-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formula_one", "0004_driver_country_code_team_country_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="circuit",
            name="country_code",
            field=models.CharField(
                blank=True,
                max_length=3,
                null=True,
                verbose_name="3 Letter country code (ISO 3166-1 alpha-3)",
            ),
        ),
    ]
