# Generated by Django 4.2.8 on 2024-01-22 19:15

from django.db import migrations, models
from jolpica.formula_one.utils import generate_season_driver_standings
import django.db.models.deletion


def create_driver_standings(apps, schema_editor):
    Season = apps.get_model("formula_one", "Season")
    DriverStanding = apps.get_model("formula_one", "DriverStanding")
    SessionEntry = apps.get_model("formula_one", "SessionEntry")
    entry = SessionEntry.objects.filter(
        session__race__round=2,
        session__race__season__year=1956,
        race_entry__team_driver__driver__reference="fangio",
        points=1.5,
    ).first()
    if entry:
        entry.is_eligible_for_points = False
        entry.save()

    driver_standings = []
    for season in Season.objects.all().select_related("championship_system"):
        driver_standings.extend(generate_season_driver_standings(season))
    DriverStanding.objects.bulk_create(driver_standings)


class Migration(migrations.Migration):
    dependencies = [
        ("formula_one", "0004_rename_championshipscheme_championshipsystem_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="session",
            old_name="point_scheme",
            new_name="point_system",
        ),
        migrations.CreateModel(
            name="DriverStanding",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("year", models.SmallIntegerField()),
                ("round", models.PositiveSmallIntegerField()),
                ("position", models.SmallIntegerField()),
                ("points", models.FloatField()),
                ("win_count", models.SmallIntegerField()),
                ("highest_finish", models.SmallIntegerField()),
                ("finish_string", models.CharField(max_length=255)),
                ("is_disqualified", models.BooleanField(default=False)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_standings",
                        to="formula_one.driver",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="driver_standings",
                        to="formula_one.race",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="driver_standings",
                        to="formula_one.season",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_standings",
                        to="formula_one.session",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="driverstanding",
            constraint=models.UniqueConstraint(
                fields=("session", "driver"),
                name="driver_standing_unique_session_driver",
            ),
        ),
        migrations.AddField(
            model_name="sessionentry",
            name="is_eligible_for_points",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(create_driver_standings, reverse_code=migrations.RunPython.noop),
    ]
