# Generated by Django 5.2.3 on 2025-08-03 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formula_one", "0005_add_dump_models"),
    ]

    operations = [
        # Remove dump models from formula_one app
        # Tables are transferred to formula_one_dump app
        migrations.DeleteModel(
            name="DumpDownload",
        ),
        migrations.DeleteModel(
            name="DumpRecord",
        ),
        migrations.DeleteModel(
            name="DumpConfiguration",
        ),
    ]
