# Generated by Django 4.2.9 on 2024-01-28 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("formula_one", "0005_rename_point_scheme_session_point_system_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DriverStanding",
            new_name="DriverChampionship",
        ),
        migrations.CreateModel(
            name="ChampionshipAdjustment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "adjustment",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Disqualified"), (2, "Excluded")]
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="championship_adjustments",
                        to="formula_one.driver",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="championship_adjustments",
                        to="formula_one.season",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="championship_adjustments",
                        to="formula_one.team",
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="RaceEntry",
            new_name="RoundEntry",
        ),
        migrations.RemoveConstraint(
            model_name="roundentry",
            name="race_entry_unique",
        ),
        migrations.AlterField(
            model_name="roundentry",
            name="race",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="round_entries",
                to="formula_one.race",
            ),
        ),
        migrations.AlterField(
            model_name="roundentry",
            name="team_driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="round_entries",
                to="formula_one.teamdriver",
            ),
        ),
        migrations.AddConstraint(
            model_name="roundentry",
            constraint=models.UniqueConstraint(
                fields=("race", "team_driver", "car_number"), name="round_entry_unique"
            ),
        ),
        migrations.RemoveConstraint(
            model_name="sessionentry",
            name="session_entry_unique_session_race_entry",
        ),
        migrations.RenameField(
            model_name="session",
            old_name="race_entries",
            new_name="round_entries",
        ),
        migrations.RenameField(
            model_name="sessionentry",
            old_name="race_entry",
            new_name="round_entry",
        ),
        migrations.AddConstraint(
            model_name="sessionentry",
            constraint=models.UniqueConstraint(
                fields=("session", "round_entry"),
                name="session_entry_unique_session_round_entry",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="race",
            name="race_unique_season_round",
        ),
        migrations.RenameField(
            model_name="race",
            old_name="round",
            new_name="number",
        ),
        migrations.AddConstraint(
            model_name="race",
            constraint=models.UniqueConstraint(
                fields=("season", "number"), name="race_unique_season_number"
            ),
        ),
        migrations.RenameModel(
            old_name="Race",
            new_name="Round",
        ),
        migrations.RenameField(
            model_name="session",
            old_name="race",
            new_name="round",
        ),
        migrations.AlterField(
            model_name="round",
            name="circuit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rounds",
                to="formula_one.circuit",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rounds",
                to="formula_one.season",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="team_drivers",
            field=models.ManyToManyField(
                related_name="rounds",
                through="formula_one.RoundEntry",
                to="formula_one.teamdriver",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="round",
            name="race_unique_season_number",
        ),
        migrations.RemoveConstraint(
            model_name="roundentry",
            name="round_entry_unique",
        ),
        migrations.RenameField(
            model_name="roundentry",
            old_name="race",
            new_name="round",
        ),
        migrations.RemoveField(
            model_name="driverchampionship",
            name="race",
        ),
        migrations.AlterField(
            model_name="driverchampionship",
            name="round",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="driver_standings",
                to="formula_one.round",
            ),
        ),
        migrations.AddConstraint(
            model_name="round",
            constraint=models.UniqueConstraint(
                fields=("season", "number"), name="round_unique_season_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="roundentry",
            constraint=models.UniqueConstraint(
                fields=("round", "team_driver", "car_number"), name="round_entry_unique"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="number",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.UniqueConstraint(
                fields=("round", "number"), name="session_unique_number_round"
            ),
        ),
    ]
