# Generated by Django 5.1.7 on 2025-03-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formula_one", "0005_circuit_country_code"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pitstop",
            name="pit_stop_unique_session_entry_lap",
        ),
        migrations.AlterField(
            model_name="driverchampionship",
            name="highest_finish",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="driverchampionship",
            name="position",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
