# Generated by Django 5.2.5 on 2025-10-05 15:04

from datetime import UTC, datetime

from django.db import migrations, models


def populate_session_timestamp_fields(apps, schema_editor):
    """Populate timestamp and has_time_data fields from existing date and time fields"""
    Session = apps.get_model("formula_one", "Session")

    sessions_to_update = []
    for session in Session.objects.all():
        # Set has_time_data based on whether time field exists
        session.has_time_data = session.time is not None

        # Populate timestamp if date exists
        if session.date:
            # Combine date and time (or use midnight if time is None)
            time = session.time if session.time else datetime.min.time()
            session.timestamp = datetime.combine(session.date, time, tzinfo=UTC)

        sessions_to_update.append(session)

    Session.objects.bulk_update(sessions_to_update, ["timestamp", "has_time_data"], batch_size=5000)


def clear_session_timestamp_fields(apps, schema_editor):
    """Clear timestamp and has_time_data fields (reverse operation)"""
    Session = apps.get_model("formula_one", "Session")
    Session.objects.all().update(timestamp=None, has_time_data=False)


class Migration(migrations.Migration):
    dependencies = [
        ("formula_one", "0006_populate_api_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="has_time_data",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Indicates whether the timestamp includes actual time data or just date with default midnight time."
                ),
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="timestamp",
            field=models.DateTimeField(
                blank=True,
                help_text="UTC datetime of the session start. If time is unknown, uses midnight (00:00:00 UTC).",
                null=True,
            ),
        ),
        migrations.RunPython(populate_session_timestamp_fields, clear_session_timestamp_fields),
    ]
