# Generated by Django 5.1.7 on 2025-03-29 11:53

from django.db import migrations, models

def convert_point_to_lat_long(apps, schema_editor):
    Circuit = apps.get_model("formula_one", "Circuit")
    for circuit in Circuit.objects.all():
        circuit.latitude = round(circuit.location.y, 7)
        circuit.longitude = round(circuit.location.x, 7)
        circuit.save()
    return

class Migration(migrations.Migration):

    dependencies = [
        (
            "formula_one",
            "0006_remove_pitstop_pit_stop_unique_session_entry_lap_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="circuit",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="circuit",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RunPython(convert_point_to_lat_long, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="circuit",
            name="location",
        ),
        migrations.RunSQL(
            sql="DROP EXTENSION IF EXISTS postgis",
            reverse_sql="CREATE EXTENSION IF NOT EXISTS postgis",
        ),
    ]
