# Generated by Django 4.2.9 on 2024-01-29 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("formula_one", "0006_rename_race_to_round_add_session_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamChampionship",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("year", models.SmallIntegerField()),
                ("round_number", models.PositiveSmallIntegerField()),
                ("position", models.SmallIntegerField(null=True)),
                ("points", models.FloatField()),
                ("win_count", models.SmallIntegerField()),
                ("highest_finish", models.SmallIntegerField(null=True)),
                ("finish_string", models.CharField(max_length=255)),
                ("is_eligible", models.BooleanField(default=False)),
                (
                    "adjustment_type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "None"), (1, "Disqualified"), (2, "Excluded")],
                        default=0,
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="driverchampionship",
            name="driver_standing_unique_session_driver",
        ),
        migrations.RemoveField(
            model_name="driverchampionship",
            name="is_disqualified",
        ),
        migrations.AddField(
            model_name="driverchampionship",
            name="adjustment_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "None"), (1, "Disqualified"), (2, "Excluded")], default=0
            ),
        ),
        migrations.AddField(
            model_name="driverchampionship",
            name="is_eligible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="driverchampionship",
            name="round_number",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="championshipadjustment",
            name="adjustment",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "None"), (1, "Disqualified"), (2, "Excluded")]
            ),
        ),
        migrations.AlterField(
            model_name="driverchampionship",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_championships",
                to="formula_one.driver",
            ),
        ),
        migrations.AlterField(
            model_name="driverchampionship",
            name="round",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="driver_championships",
                to="formula_one.round",
            ),
        ),
        migrations.AlterField(
            model_name="driverchampionship",
            name="season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="driver_championships",
                to="formula_one.season",
            ),
        ),
        migrations.AlterField(
            model_name="driverchampionship",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_championships",
                to="formula_one.session",
            ),
        ),
        migrations.AddConstraint(
            model_name="driverchampionship",
            constraint=models.UniqueConstraint(
                fields=("session", "driver"),
                name="driver_championship_unique_session_driver",
            ),
        ),
        migrations.AddField(
            model_name="teamchampionship",
            name="round",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_championships",
                to="formula_one.round",
            ),
        ),
        migrations.AddField(
            model_name="teamchampionship",
            name="season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_championships",
                to="formula_one.season",
            ),
        ),
        migrations.AddField(
            model_name="teamchampionship",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_championships",
                to="formula_one.session",
            ),
        ),
        migrations.AddField(
            model_name="teamchampionship",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_championships",
                to="formula_one.team",
            ),
        ),
        migrations.AddConstraint(
            model_name="teamchampionship",
            constraint=models.UniqueConstraint(
                fields=("session", "team"), name="team_championship_unique_session_team"
            ),
        ),
    ]
