# Generated by Django 5.2.7 on 2025-10-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formula_one", "0007_session_has_time_data_session_timestamp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="session",
            options={"ordering": ["timestamp", "type"]},
        ),
        migrations.RemoveField(
            model_name="session",
            name="date",
        ),
        migrations.RemoveField(
            model_name="session",
            name="time",
        ),
    ]
