# Generated by Django 5.2.7 on 2025-10-05 22:10

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formula_one", "0008_alter_session_options_remove_session_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(
                blank=True,
                help_text="IANA timezone identifier for the session location (e.g., 'Europe/Monaco', 'Asia/Singapore').",
                null=True,
            ),
        ),
    ]
