# Generated by Django 4.2.10 on 2024-03-09 19:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "formula_one",
            "0008_remove_championshipsystem_championship_point_scheme_unique_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driverchampionship",
            name="finish_string",
        ),
        migrations.RemoveField(
            model_name="teamchampionship",
            name="finish_string",
        ),
    ]
