# Generated by Django 5.2.7 on 2025-10-18 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formula_one", "0009_session_timezone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="round",
            options={"ordering": ["season__year", "number"]},
        ),
        migrations.AlterModelOptions(
            name="season",
            options={"ordering": ["year"]},
        ),
    ]
