# Generated by Django 5.2.8 on 2026-01-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formula_one", "0010_alter_round_options_alter_season_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="primary_color",
            field=models.CharField(
                blank=True, max_length=7, null=True, verbose_name="Hex color code"
            ),
        ),
    ]
