# Generated by Django 5.2.8 on 2026-03-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formula_one", "0012_alter_session_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="championshipsystem",
            name="eligibility",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Entry must score at least 1 championship point"),
                    (2, "Entry must have a classified finish in at least 1 round"),
                    (
                        3,
                        "Entry must have a classified finish or qualifying finish in at least 1 round",
                    ),
                ]
            ),
        ),
    ]
