# Generated by Django 5.2.16 on 2026-09-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formula_one", "0013_alter_championshipsystem_eligibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="completed_distance",
            field=models.FloatField(
                blank=True,
                db_comment="Distance covered by finishing all completed laps, in kilometres.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="completed_laps",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sessionentry",
            name="driver_of_the_day_percentage",
            field=models.FloatField(
                blank=True,
                db_comment="Share of driver of the day votes received, 0-100.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sessionentry",
            name="driver_of_the_day_winner",
            field=models.BooleanField(
                blank=True,
                db_comment="Only True is stored; non-winning entries and missing entries are NULL.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("driver_of_the_day_winner__isnull", False)),
                fields=("session",),
                name="session_entry_unique_driver_of_the_day_winner",
                violation_error_message="Only one session entry per session can be the driver of the day winner.",
            ),
        ),
    ]
