# Generated by Django 4.2.6 on 2023-11-13 22:06

from django.db import migrations
from django.core.management import call_command
from jolpica.formula_one.standings import SeasonData, Group



def add_test_data(apps, schema_editor):
    call_command("loaddata", "tests/fixtures/users.json")
    call_command("loaddata", "tests/fixtures/2000s_data.json.gz")
    call_command("loaddata", "tests/fixtures/legacy_data.json.gz")


def create_driver_standings(apps, schema_editor):
    Season = apps.get_model("formula_one", "Season")
    DriverChampionship = apps.get_model("formula_one", "DriverChampionship")
    TeamChampionship = apps.get_model("formula_one", "TeamChampionship")

    team_standings = []
    driver_standings = []
    for season in Season.objects.all().select_related("championship_system"):
        season_data = SeasonData.from_season(season)
        driver_standings.extend(season_data.generate_standings(Group.DRIVER))
        team_standings.extend(season_data.generate_standings(Group.TEAM))
    DriverChampionship.objects.bulk_create(driver_standings)
    TeamChampionship.objects.bulk_create(team_standings)

class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(add_test_data),
        migrations.RunPython(create_driver_standings),
    ]
