# Generated by Django 4.2.6 on 2023-11-13 22:06

import subprocess

# django settings
from django.conf import settings
from django.core.management import call_command
from django.db import migrations

from jolpica.formula_one.standings import Group, SeasonData, update_championship_standings_in_db


def add_test_data(apps, schema_editor):
    call_command("loaddata", "tests/fixtures/users.json")

    command = [
        "psql",
        "-h",
        settings.DATABASES["default"]["HOST"],
        "-d",
        settings.DATABASES["default"]["NAME"],
        "-U",
        settings.DATABASES["default"]["USER"],
        "-f",
        "tests/fixtures/db/tables.sql",
    ]
    subprocess.run(command, check=True)

    command = [
        "psql",
        "-h",
        settings.DATABASES["default"]["HOST"],
        "-d",
        settings.DATABASES["default"]["NAME"],
        "-U",
        settings.DATABASES["default"]["USER"],
        "-f",
        "tests/fixtures/import.sql",
    ]
    subprocess.run(command, check=True)

    command = [
        "sh", 
        "tests/fixtures/fix_auto_increments.sh",
    ]
    subprocess.run(command, check=True)


def create_driver_standings(apps, schema_editor):
    Season = apps.get_model("formula_one", "Season")

    update_championship_standings_in_db(set(Season.objects.values_list("year", flat=True)))


class Migration(migrations.Migration):
    dependencies = [
        (
            "formula_one",
            "0007_circuit_latitude_circuit_longitude",
        ), 
    ]

    operations = [
        migrations.RunPython(add_test_data),
        migrations.RunPython(create_driver_standings),
    ]
