# Generated by Django 4.2.6 on 2023-11-13 22:06

from django.db import migrations
from django.core.management import call_command
from jolpica.formula_one.utils import generate_season_driver_standings



def add_test_data(apps, schema_editor):
    call_command("loaddata", "tests/fixtures/users.json")
    call_command("loaddata", "tests/fixtures/2000s_data.json.gz")
    call_command("loaddata", "tests/fixtures/legacy_data.json.gz")


def create_driver_standings(apps, schema_editor):
    Season = apps.get_model("formula_one", "Season")
    DriverChampionship = apps.get_model("formula_one", "DriverChampionship")

    driver_standings = []
    for season in Season.objects.all().select_related("championship_system"):
        driver_standings.extend(generate_season_driver_standings(season))
    DriverChampionship.objects.bulk_create(driver_standings)

class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(add_test_data),
        migrations.RunPython(create_driver_standings),
    ]
