# Generated by Django 3.2.6 on 2021-08-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ergast", "0007_auto_20210808_0016"),
    ]

    operations = [
        migrations.RenameField(
            model_name="results",
            old_name="id",
            new_name="resultId",
        ),
        migrations.RemoveField(
            model_name="seasons",
            name="id",
        ),
        migrations.AlterField(
            model_name="seasons",
            name="year",
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name="Primary key e.g. 1950"),
        ),
    ]
