# Generated by Django 4.2.6 on 2023-10-15 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ergast", "0014_auto_20230924_2047"),
    ]

    operations = [
        migrations.CreateModel(
            name="SprintResults",
            fields=[
                (
                    "resultId",
                    models.AutoField(
                        db_column="resultId", primary_key=True, serialize=False, verbose_name="Primary key"
                    ),
                ),
                ("number", models.IntegerField(blank=True, null=True, verbose_name="Driver number")),
                ("grid", models.IntegerField(verbose_name="Starting grid position")),
                (
                    "position",
                    models.IntegerField(blank=True, null=True, verbose_name="Official classification, if applicable"),
                ),
                (
                    "positionText",
                    models.CharField(
                        blank=True,
                        db_column="positionText",
                        max_length=255,
                        verbose_name='Driver position string e.g. "1" or "R"',
                    ),
                ),
                (
                    "positionOrder",
                    models.IntegerField(
                        db_column="positionOrder", verbose_name="Driver position for ordering purposes"
                    ),
                ),
                ("points", models.FloatField(verbose_name="Driver points for race")),
                ("laps", models.IntegerField(verbose_name="Number of completed laps")),
                ("time", models.CharField(blank=True, max_length=255, null=True, verbose_name="Finishing time or gap")),
                (
                    "milliseconds",
                    models.IntegerField(blank=True, null=True, verbose_name="Finishing time in milliseconds"),
                ),
                (
                    "fastestLap",
                    models.IntegerField(
                        blank=True, db_column="fastestLap", null=True, verbose_name="Lap number of fastest lap"
                    ),
                ),
                (
                    "fastestLapTime",
                    models.CharField(
                        blank=True,
                        db_column="fastestLapTime",
                        max_length=255,
                        null=True,
                        verbose_name='Fastest lap time e.g. "1:27.453"',
                    ),
                ),
                (
                    "constructorId",
                    models.ForeignKey(
                        db_column="constructorId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ergast.constructors",
                        verbose_name="Foreign key link to constructors table",
                    ),
                ),
                (
                    "driverId",
                    models.ForeignKey(
                        db_column="driverId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ergast.drivers",
                        verbose_name="Foreign key link to drivers table",
                    ),
                ),
                (
                    "raceId",
                    models.ForeignKey(
                        db_column="raceId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ergast.races",
                        verbose_name="Foreign key link to races table",
                    ),
                ),
                (
                    "statusId",
                    models.ForeignKey(
                        db_column="statusId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ergast.status",
                        verbose_name="Foreign key link to status table",
                    ),
                ),
            ],
            options={
                "db_table": "ergast_sprint_results",
            },
        ),
    ]
